apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: petclinic
    labels:
      app: petclinic
  spec:
    containers:
    - name: server
      image: mariolet/petclinic
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        limits:
        memory: 512Mi
    - name: mysql
      image: centos/mysql-57-centos7
      env:
      - name: MYSQL_USER
        value: petclinic
      - name: MYSQL_PASSWORD
        value: petclinic
      - name: MYSQL_ROOT_PASSWORD
        value: petclinic
      - name: MYSQL_DATABASE
        value: petclinic
      volumeMounts:
      - mountPath: /var/lib/mysql/data
        name: mysql-storage
      ports:
      - containerPort: 3306
        protocol: TCP
      resources:
        limits:
        memory: 512Mi
    volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-storage
- kind: Service
  apiVersion: v1
  metadata:
    name: petclinic
    labels:
      app: petclinic
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      app: petclinic
- kind: Service
  apiVersion: v1
  metadata:
    name: mysql
    labels:
      app: petclinic
  spec:
    ports:
      - name: mysql
        port: 3306
        targetPort: 3360
    selector:
      app: petclinic
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: petclinic
    name: mysql-storage
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi`
